# Table of contents <a name="back"></a>

13. [Manual Data Loading](#man)
14. [DataFrames](#df)
15. [More about Data-Frames: Selecting Rows and Columns](#sel)
16. [Even More about DataFrames: Column Names](#col)
17. [The apply() Function](#appl)
18. [Joins](#joins)
19. [.values vs .as_matric()](#val)

<a name="man"></a>
[back](#back)

# 13. Manual Data Loading

https://github.com/lazyprogrammer/machine_learning_examples/tree/master/linear_regression_class

In [11]:
import pandas as pd
import numpy as np

In [4]:
import os
os.getcwd()

'C:\\Users\\basia\\Udemy Lazy Programmer Courses\\00 The Numpy Stack in Python'

In [5]:
X = [] # create and empty list

In [6]:
import numpy as np
for line in open("data_2d.csv"): # loop through each line
    row = line.split(',')
    sample = map(float, row)
    X.append(sample)

In [7]:
X

In [8]:
X = np.array(X)

In [9]:
X.shape

(100,)

In [10]:
import numpy as np
for line in open("data_2d.csv"): # loop through each line
    row = line.split(',')
    sample = map(float, row)
    X.append(sample)


AttributeError: 'numpy.ndarray' object has no attribute 'append'

<a name="df"></a>
[back](#back)

# 14. DataFrames

Pandas is a lot like R. The goal of this lecture is to show the featres thay are used the most often in data science

In [12]:
import pandas as pd

In [13]:
X = pd.read_csv("data_2d.csv", header=None)

In [14]:
type(X) # check what data type this function returns

pandas.core.frame.DataFrame

Datatrames come with some useful functions:

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB


In [17]:
X.head(3) # prints out the first n rows

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108

<a name="sel"></a>
[back](#back)

# 15. More about DataFrames: Selecting Rows and Columns

We can convert the DataFrame into Matrix:

In [18]:
M = X.as_matrix()

C:\Users\basia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [19]:
type(M)

numpy.ndarray

But let's go back to working with a DataFrame

In [20]:
X[0] # entire column of X, where the column name is zero

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, Length: 100, dt

In [21]:
X.head()

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

#### Remember this distinction:
* When we use Numpy arrays with [], the first index gives us the row.
* When we use DataFrames with [], we're only allowed one index, and that index is the column name for the column we're going to get back.

In [36]:
A = np.array([ [1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [37]:
A[0]

array([1, 2])

In [39]:
X[0]

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, Length: 100, dt

In [66]:
type(X[0]) # let's see what data type X[0] gives us

pandas.core.series.Series

Pandas DataFrames are for 2D objects.
Pandas Series are for 1D objects.

How to get a row?

In [69]:
X.iloc[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [70]:
X.ix[0]

C:\Users\basia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [71]:
type(X.iloc[0]) # these are also Series

pandas.core.series.Series

Select more that one column at a time

In [40]:
X[[0,2]] # the zeroth and the second column

0           2
0   17.930201  320.259530
1   97.144697  404.634472
2   81.775901  181.485108
3   55.854342  321.773638
4   49.366550  322.465486
5    3.192702   94.618811
6   49.200784  356.348093
7   21.882804  181.653769
8   79.509863  423.557743
9   88.153887  369.229245
10  60.743854  427.605804
11  67.415582  292.471822
12  48.318116  395.529811
13  28.829972  319.031348
14  43.853743  287.428144
15  25.313694  292.768909
16  10.807727  159.663308
17  98.365746  438.798964
18  29.146910  250.986309
19  65.100302  231.711508
20  24.644113  163.398161
21  37.559805   83.480155
22  88.164506  466.265806
23  13.834621  100.886430
24  64.410844  365.641048
25  68.925992  426.140015
26  39.488442  235.532389
27  52.463178  283.291640
28  48.484787  298.581440
29   8.062088  309.234109
..        ...         ...
70  30.187692   89.539008
71  11.788418  181.550683
72  18.292424  224.773383
73  96.712668  219.567094
74  31.012739  298.490216
75  11.397261  199.944045
76  17.392556   43.915692
77  72.182694  256.068378
78  73.980021  159.372581
79  94.493058  447.132704
80  84.562821  233.078830
81  51.742474  131.070180
82  53.748590  298.814333
83  85.050835  451.803523
84  46.777250  368.366436
85  49.758434  254.706774
86  24.119257  168.308433
87  27.201576  146.342260
88   7.009596  176.810149
89  97.646950  219.160280
90   1.382983  252.905653
91  22.323530  127.570479
92  45.045406  375.822340
93  40.163991   80.389019
94  53.182740  142.718183
95  46.456779  336.876154
96  77.130301  438.460586
97  68.600608  355.900287
98  41.693887  284.834637
99   4.142669  168.034401

[100 rows x 2 columns]

Select rows with specific criteria

In [44]:
X[ X[0] < 5] # Find all the rows where the data for the 0th column is less than 5

0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401

In [75]:
X[0] < 5

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...  
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79    False
80    False
81    False
82    False
83    False
84    False
85    False
86    False
87    False
88    False
89    False
90     True
91    False
92    False
93    False
94    False
95    False
96    False
97    False
98    False
99     True
Name: 0, Length: 100, dtype: bool

In [76]:
type(X[0] < 5)

pandas.core.series.Series

Here's what's really weird about this:
We've already seen that the square bracket notation [] lets us choose columns, but oddly, when we pass in THIS Series, with the same number of rows as a DataFrame, we are selecting rows. But both are using the [] notation.

<a name="col"></a>
[back](#back)

# 16. Even More about DataFrames: Column Names

https://github.com/lazyprogrammer/machine_learning_examples/tree/master/airline

In [20]:
import pandas as pd

Skip footer doesn't work with the default engine, which is in C, so we need to explicitly pass in engine = python

In [38]:
df = pd.read_csv("international-airline-passengers.csv", engine="python", skipfooter=3)

In [39]:
df.head(3)

Month  \
0  1949-01   
1  1949-02   
2  1949-03   

   International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60  
0                                                112                               
1                                                118                               
2                                                132

In [40]:
df.columns

Index(['Month', 'International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60'], dtype='object')

The column names are ugly. We are going to reassign them, and pass them a list.

In [41]:
df.columns = ["month", "passengers"]
df.columns

Index(['month', 'passengers'], dtype='object')

In [42]:
df['month']

0      1949-01
1      1949-02
2      1949-03
3      1949-04
4      1949-05
5      1949-06
6      1949-07
7      1949-08
8      1949-09
9      1949-10
10     1949-11
11     1949-12
12     1950-01
13     1950-02
14     1950-03
15     1950-04
16     1950-05
17     1950-06
18     1950-07
19     1950-08
20     1950-09
21     1950-10
22     1950-11
23     1950-12
24     1951-01
25     1951-02
26     1951-03
27     1951-04
28     1951-05
29     1951-06
        ...   
113    1958-06
114    1958-07
115    1958-08
116    1958-09
117    1958-10
118    1958-11
119    1958-12
120    1959-01
121    1959-02
122    1959-03
123    1959-04
124    1959-05
125    1959-06
126    1959-07
127    1959-08
128    1959-09
129    1959-10
130    1959-11
131    1959-12
132    1960-01
133    1960-02
134    1960-03
135    1960-04
136    1960-05
137    1960-06
138    1960-07
139    1960-08
140    1960-09
141    1960-10
142    1960-11
Name: month, Length: 143, dtype: object

We have an alternative method when the columns are strings. This won't work if the columns include spaces.

In [43]:
df.passengers

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ... 
113    435
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
Name: passengers, Length: 143, dtype: int64

The following adds a new column called 'ones' and each row will have a value 1 for that column.

In [44]:
df['ones'] = 1

In [45]:
df['x1'] = 2
df['x2'] = 3

In [46]:
df.head(3)

month  passengers  ones  x1  x2
0  1949-01         112     1   2   3
1  1949-02         118     1   2   3
2  1949-03         132     1   2   3

<a name="appl"></a>
[back](#back)

# 17. The apply() Function

How to assign a new column value, based on the other data in its row.

In [47]:
df['x1x2'] = df.apply(lambda row: row['x1']*row['x2'], axis=1)

In [48]:
df.head(3)

month  passengers  ones  x1  x2  x1x2
0  1949-01         112     1   2   3     6
1  1949-02         118     1   2   3     6
2  1949-03         132     1   2   3     6

This is equivalent to doing a for loop, but never actually do this because for loops are very slow.

In [49]:
interactions = []
for idx, row in df.iterrows():
    x1x2 = row['x1'] * row['x2']
    interactions.append(x1x2)
df['x1x2_v2'] = interactions

Now let's apply all this knowledge do our dataset.

In [50]:
from datetime import datetime

Test this script time function to make sure it does what we expect.

In [52]:
datetime.strptime("1949-02","%Y-%m")

datetime.datetime(1949, 2, 1, 0, 0)

Now let's put this into apply.

In [53]:
df['df'] = df.apply(lambda row: datetime.strptime(row['month'], "%Y-%m"), axis=1)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 8 columns):
month         143 non-null object
passengers    143 non-null int64
ones          143 non-null int64
x1            143 non-null int64
x2            143 non-null int64
x1x2          143 non-null int64
x1x2_v2       143 non-null int64
df            143 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(6), object(1)
memory usage: 9.0+ KB


<a name="joins"></a>
[back](#back)

# 18. Joins

https://github.com/lazyprogrammer/machine_learning_examples/tree/master/numpy_class

In [56]:
import pandas as pd

In [60]:
t1 = pd.read_csv('table1.csv')
t2 = pd.read_csv('table2.csv')

In [61]:
t1

user_id            email  age
0        1  alice@gmail.com   20
1        2    bob@gmail.com   25
2        3  carol@gmail.com   30

In [62]:
t2

user_id  ad_id  click
0         1      1      1
1         1      2      0
2         1      5      0
3         2      3      0
4         2      4      1
5         2      1      0
6         3      2      0
7         3      1      0
8         3      3      0
9         3      4      0
10        3      5      1

Let's join these tables on user_id column.

In [64]:
m = pd.merge(t1, t2, on='user_id')

In [65]:
m

user_id            email  age  ad_id  click
0         1  alice@gmail.com   20      1      1
1         1  alice@gmail.com   20      2      0
2         1  alice@gmail.com   20      5      0
3         2    bob@gmail.com   25      3      0
4         2    bob@gmail.com   25      4      1
5         2    bob@gmail.com   25      1      0
6         3  carol@gmail.com   30      2      0
7         3  carol@gmail.com   30      1      0
8         3  carol@gmail.com   30      3      0
9         3  carol@gmail.com   30      4      0
10        3  carol@gmail.com   30      5      1

<a name="val"></a>
[back](#back)

# 19. .values vs .as_matric()

In [66]:
import pandas as pd
import numpy as np

In [68]:
df = pd.DataFrame([[1,2],[3,4]])

In [69]:
df

0  1
0  1  2
1  3  4

Now let's try using as_matrix to obtain a Numpy array.

In [70]:
df.as_matrix()

C:\Users\basia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[1, 2],
       [3, 4]], dtype=int64)

In [71]:
df.values

array([[1, 2],
       [3, 4]], dtype=int64)

Numpy array is not the same as numpy matrix and so we'd expect a function named as_matrix to return a matrix, rather than a Numpy array, but in fact the array is more useful to use because that's what's normally used in machine learning. Matrices are rare.

<a name="val"></a>
[back](#back)