# Table of contents <a name="back"></a>

4. [Lists vs Arrays](#listsvsarrays)
    1. [Python list](#pythonlist)
    2. [NumPy array](#numpyarray)
5. [Dot product 1: for loop vs cosine method vs dot function](#dot1)
6. [Dot product 2: Speed comparison](#dot2)
7. [Vectors and Matrices](#vandm)
8. [Generating Martices to Work With](#gen)
9. [Matrix Products](#mat)
10. [More Matrix Operations](#morem)
11. [Solving a Linear System](#linear)
12. [Word Problem](#word)
13. [Manual Data Loading](#man)

In [ ]:
# !jupyter nbconvert --to html "Lesson1_homework.ipynb"

# 4. Lists vs Arrays <a name="listsvsarrays"></a>

In [3]:
import pandas as pd
import numpy as np

<a name="pythonlist"></a>
[back](#back)

### Python list 

In [4]:
L = [1,2,3]

In [5]:
# print the contents of a list
for e in L:
    print(e)

1
2
3


In [6]:
# append to a list, method 1
L.append(4)
L

[1, 2, 3, 4]

In [7]:
# append to a list, method 2 - join two lisit together
L = L + [5]
L

[1, 2, 3, 4, 5]

In [8]:
# addition with Python list, acts like appending
L + L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
# vector addition with Python list
L2 = []
for e in L:
    L2.append(e + e)
L2

[2, 4, 6, 8, 10]

In [10]:
4. [Lists vs Arrays](#listsvsarrays)

SyntaxError: invalid syntax (<ipython-input-10-778b6fe09709>, line 1)

<a name="numpyarray"></a>
[back](#back)

### NumPy array 

Most functions add element wise

In [11]:
A = np.array([1,2,3])

In [12]:
for e in A:
    print(e)

1
2
3


In [13]:
# vector addition with NumPy array
A + A

array([2, 4, 6])

In [14]:
# vector multiplication with Numpy array
2*A

array([2, 4, 6])

In [15]:
# element wise squaring of every element in a vector
A**2

array([1, 4, 9], dtype=int32)

In [16]:
# square root
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [17]:
# log
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [18]:
# exponential
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

<a name="dot1"></a>
[back](#back)

# 5. Dot product 1: for loop vs cosine method vs dot function <a name="dot1"></a>

<img src="img01/dot.png" alt="drawing" width="200" style="float: left">

In [19]:
# method 1, for loop
a = np.array([1,2])
b = np.array([2,1])
dot = 0
for e, f in zip(a, b):
    dot += e*f
# The zip() function takes iterables (can be zero or more), makes iterator that aggregates elements 
# based on the iterables passed, and returns an iterator of tuples

In [20]:
dot

4

In [21]:
# element-wise multiplication of two arrays (so arrays have to be the same size)
a*b

array([2, 2])

In [22]:
# method 2, cosine method
np.sum(a*b) # this gives the dot product of the two arrays

4

In [23]:
# sum fuction is an instance method of the NumPy array itself, so an
# alternative way of doing this is 
(a*b).sum()

4

In [24]:
# method 3, dot function
np.dot(a, b)

4

In [25]:
# the dot function is also an instance method of the NumPy array,
# so we can call it on the object itself
a.dot(b)

4

In [26]:
b.dot(a)

4

In [27]:
# Now let's use the alternative definition of the dot product.
# So calculate the angle between a and b. For this we need to 
# figure out how to calculate the length of the vector.
# It's just the square root of the sum of each element squared.
amag = np.sqrt( (a*a).sum() )

In [28]:
amag # magnitude of a

2.23606797749979

In [29]:
amag = np.linalg.norm(a)

In [30]:
amag

2.23606797749979

In [31]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [32]:
cosangle

0.7999999999999998

In [33]:
angle = np.arccos(cosangle)

In [34]:
angle # in radians

0.6435011087932847

<a name="dot2"></a>
[back](#back)

# 6. Dot product 2: Speed comparison 

In [35]:
import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

# the first method is going to use a for loop, multiply each of the
# corresponding elements one dimension at a time
# and accumulate the result
def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e*f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

# the second method is going to use NumPy's dot function
t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

# at the end we'll divide the first elapsed time by the second elapsed time
# and that will tell us approximately how many times faster
# the NumPy method is
print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

# the lesson is, don't use a for loop, if you can avoid it.

dt1 / dt2: 42.64207402840132


In [78]:
b = np.random.randn(10)
b

array([ 0.52724556,  0.75084295,  1.02216545, -0.2898255 ,  1.27277231,
       -2.35634907,  0.40615372,  1.58141966, -0.10291664,  1.26917704])

<a name="vandm"></a>
[back](#back)

# 7. Vectors and Matrices 

A matrix is like a 2-dimensional vector. A more general way to think about this is 
* a matrix is a 2-dimensional mathematical object that contains numbers. 
* a vector is a 1-dimensional mathematical object that contains numbers.

One way to think of a matrix is that it's a two dimensional array.
Another way to think of this, is that it's a list of lists. In fact, you can use a list of lists to initialize a matrix.

In [37]:
# the first index is the row, the second index is the column
M = np.array([ [1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [38]:
# Let's create an actual list of lists for reference
L = [ [1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [39]:
# Let's say we want to get an element of the matrix.
# Let's say we want to get the "1".
# With a Python list, we would first index the row, 
# and that would give us the first list, which contains "1, 2"
L[0]

[1, 2]

In [40]:
# now out of this list we want the first element
L[0][0]

1

In [41]:
# We can do the same thing with a NumPy array
M[0][0]

1

In [42]:
# but there's a shorthand notation which looks mora like Matlab with a comma
M[0,0]

1

In [43]:
# note that there is an actual data type in NumPy called matrix
M2 = np.matrix([ [1,2], [3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [44]:
type(M2)

numpy.matrixlib.defmatrix.matrix

In [45]:
# it is actually recommended to use arrays and if you see
# a matrix type, it's usually good to convert it to an array.
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [46]:
# Even though it's an array, it still gives us convenient matrix 
# operations, such as transpose.
A.T

array([[1, 3],
       [2, 4]])

<a name="gen"></a>
[back](#back)

# 8. Generating Martices to Work With 

In [47]:
# array of zeros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
# 10 by 10 matrix of zeros
# the function still takes in one input - a tuple containing each dimension
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
# array of ones
O = np.ones(10)
O

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
O = np.ones((3,3))
O

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# random numbers (uniform distribution)
R = np.random.random((3,3))
R

array([[0.41774423, 0.23836098, 0.68379819],
       [0.37568845, 0.18150949, 0.72731766],
       [0.23367716, 0.08121061, 0.71997845]])

In [52]:
# random numbers (Gaussian distribution with mean 0 and variance 1)
# this function takes in two individual arguments instead of a tuple,
# so, single quote, and each dimension separately
G = np.random.randn(3,3)
G

array([[-0.41299946,  0.38752957,  1.38569763],
       [-1.29491521, -0.83911821,  0.53406219],
       [ 0.83393604, -0.49098342,  0.26959733]])

In [53]:
G.mean()

0.041422940871358095

In [54]:
G.var()

0.655645205282865

In [55]:
type(G)

numpy.ndarray

<a name="mat"></a>
[back](#back)

# 9. Matrix Products 

<img src="img01/matrix_multipl.png" alt="drawing" width="200" style="float: left">

In Numpy, the asterisk (*) means element by element multiplication and a dot (.) means matrix multiplication

<a name="morem"></a>
[back](#back)

# 10. More Matrix Operations 

In [56]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [57]:
# Matrix inverse
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We can check that the inverse has been calculated correctly by multiplying Ainv.

In [58]:
# method 1
np.dot(A, Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [59]:
# method 2
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [60]:
# method 3
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

<a name="linear"></a>
[back](#back)

# 11. Solving a Linear System 

<img src="img01/linear_system.png" alt="drawing" width="350" style="float: left">

In [61]:
A = np.array([[1,2],[3,4]])
b = np.array([1,2])

In [62]:
A

array([[1, 2],
       [3, 4]])

In [63]:
b

array([1, 2])

In [64]:
x = np.linalg.inv(A).dot(b)

In [65]:
x

array([2.22044605e-16, 5.00000000e-01])

In [66]:
x = np.linalg.solve(A, b)

In [67]:
x

array([0. , 0.5])

<a name="word"></a>
[back](#back)

# 12. Word Problem 

In [68]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200, 5050])

In [69]:
np.linalg.solve(A,b)

array([1500.,  700.])

<a name="man"></a>
[back](#back)